PRAGMA foreign_keys=ON;

create view if not exists horarioSemanaEmCausaAuxilia as select Dia_folga,Data_segunda,turnoDiurno,turnoNoturno,Hora,Data from Horario,Cirurgia where NEW.Cirurgia = Cirurgia.idServico and NEW.Enfermeiro = Horario.idFuncionario and (cast(strftime('%J',Cirurgia.Data) as int) - cast(strftime('%J',Horario.Data_segunda) as int)) < 7;

create view if not exists trabalhoTurnoAuxilia as select * from horarioSemanaEmCausaAuxilia where (((cast(strftime('%H',horarioSemanaEmCausaAuxilia.Hora)as int) > 20 or cast(strftime('%H',horarioSemanaEmCausaAuxilia.Hora)as int) < 6) and horarioSemanaEmCausaAuxilia.turnoNoturno = 1) or ((cast(strftime('%H',horarioSemanaEmCausaAuxilia.Hora)as int) > 6 and cast(strftime('%H',horarioSemanaEmCausaAuxilia.Hora)as int) < 20) and horarioSemanaEmCausaAuxilia.turnoDiurno = 1));

create view if not exists trabalhoFolgaAuxilia as select * from horarioSemanaEmCausaAuxilia where (((cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data_segunda) as int)) = 0 and horarioSemanaEmCausaAuxilia.Dia_folga not like 'Segunda') or ((cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data_segunda) as int)) = 1 and horarioSemanaEmCausaAuxilia.Dia_folga not like 'Terça') or ((cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data_segunda) as int)) = 2 and horarioSemanaEmCausaAuxilia.Dia_folga not like 'Quarta') or ((cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data_segunda) as int)) = 3 and horarioSemanaEmCausaAuxilia.Dia_folga not like 'Quinta') or ((cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data_segunda) as int)) = 4 and horarioSemanaEmCausaAuxilia.Dia_folga not like 'Sexta') or ((cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data_segunda) as int)) = 5 and horarioSemanaEmCausaAuxilia.Dia_folga not like 'Sábado') or ((cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaAuxilia.Data_segunda) as int)) = 6 and horarioSemanaEmCausaAuxilia.Dia_folga not like 'Domingo'));

create trigger cirurgiaEnfermeiroDisponivel
after insert on Auxilia
when not exists (select * from horarioSemanaEmCausaAuxilia) or not exists (select * from trabalhoTurnoAuxilia) or not exists (select * from trabalhoFolgaAuxilia)
begin
select raise(rollback,'Esse funcionario nao estava a trabalhar nessa data e hora');
end;