PRAGMA foreign_keys=ON;

create view if not exists horarioSemanaEmCausaRealizam as select Dia_folga,Data_segunda,turnoDiurno,turnoNoturno,Hora,Data from Horario,Cirurgia where NEW.Cirurgia = Cirurgia.idServico and NEW.Medico = Horario.idFuncionario and (cast(strftime('%J',Cirurgia.Data) as int) - cast(strftime('%J',Horario.Data_segunda) as int)) < 7;

create view if not exists trabalhoTurnoRealizam as select * from horarioSemanaEmCausaRealizam where (((cast(strftime('%H',horarioSemanaEmCausaRealizam.Hora)as int) > 20 or cast(strftime('%H',horarioSemanaEmCausaRealizam.Hora)as int) < 6) and horarioSemanaEmCausaRealizam.turnoNoturno = 1) or ((cast(strftime('%H',horarioSemanaEmCausaRealizam.Hora)as int) > 6 and cast(strftime('%H',horarioSemanaEmCausaRealizam.Hora)as int) < 20) and horarioSemanaEmCausaRealizam.turnoDiurno = 1));

create view if not exists trabalhoFolgaRealizam as select * from horarioSemanaEmCausaRealizam where (((cast(strftime('%J',horarioSemanaEmCausaRealizam.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaRealizam.Data_segunda) as int)) = 0 and horarioSemanaEmCausaRealizam.Dia_folga not like 'Segunda') or ((cast(strftime('%J',horarioSemanaEmCausaRealizam.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaRealizam.Data_segunda) as int)) = 1 and horarioSemanaEmCausaRealizam.Dia_folga not like 'Terça') or ((cast(strftime('%J',horarioSemanaEmCausaRealizam.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaRealizam.Data_segunda) as int)) = 2 and horarioSemanaEmCausaRealizam.Dia_folga not like 'Quarta') or ((cast(strftime('%J',horarioSemanaEmCausaRealizam.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaRealizam.Data_segunda) as int)) = 3 and horarioSemanaEmCausaRealizam.Dia_folga not like 'Quinta') or ((cast(strftime('%J',horarioSemanaEmCausaRealizam.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaRealizam.Data_segunda) as int)) = 4 and horarioSemanaEmCausaRealizam.Dia_folga not like 'Sexta') or ((cast(strftime('%J',horarioSemanaEmCausaRealizam.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaRealizam.Data_segunda) as int)) = 5 and horarioSemanaEmCausaRealizam.Dia_folga not like 'Sábado') or ((cast(strftime('%J',horarioSemanaEmCausaRealizam.Data) as int) - cast(strftime('%J',horarioSemanaEmCausaRealizam.Data_segunda) as int)) = 6 and horarioSemanaEmCausaRealizam.Dia_folga not like 'Domingo'));

create trigger cirurgiaMedicoDisponivel
after insert on Realizam
when not exists (select * from horarioSemanaEmCausaRealizam) or not exists (select * from trabalhoTurnoRealizam) or not exists (select * from trabalhoFolgaRealizam)
begin
select raise(rollback,'Esse funcionario nao estava a trabalhar nessa data e hora');
end;